apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
  selector:
    app: spring-boot-app
